export interface ExtractTemplate {
  id: string;
  name: string;
  description: string;
  prompt: string;
  schema: string;
}

export const extractTemplates: ExtractTemplate[] = [
  {
    id: 'news-article',
    name: 'News Article',
    description: 'Extract structured data from news articles',
    prompt: 'Extract the news article data including title, author, publication date, main content, category, and tags.',
    schema: JSON.stringify({
      type: 'object',
      properties: {
        title: { type: 'string' },
        author: { type: 'string' },
        publishDate: { type: 'string', description: 'ISO 8601 date' },
        content: { type: 'string', description: 'Main article text' },
        summary: { type: 'string', description: 'Brief summary in 2-3 sentences' },
        category: { type: 'string' },
        tags: { type: 'array', items: { type: 'string' } },
        imageUrl: { type: 'string' },
      },
      required: ['title', 'content'],
    }, null, 2),
  },
  {
    id: 'product-page',
    name: 'Product Page',
    description: 'Extract product details from e-commerce pages',
    prompt: 'Extract product information including name, price, description, images, rating, and availability.',
    schema: JSON.stringify({
      type: 'object',
      properties: {
        name: { type: 'string' },
        price: { type: 'number' },
        currency: { type: 'string' },
        description: { type: 'string' },
        images: { type: 'array', items: { type: 'string' } },
        rating: { type: 'number', description: 'Out of 5' },
        reviewCount: { type: 'number' },
        availability: { type: 'string', enum: ['in_stock', 'out_of_stock', 'pre_order'] },
        brand: { type: 'string' },
        sku: { type: 'string' },
        categories: { type: 'array', items: { type: 'string' } },
      },
      required: ['name', 'price'],
    }, null, 2),
  },
  {
    id: 'blog-post',
    name: 'Blog Post',
    description: 'Extract blog post content and metadata',
    prompt: 'Extract the blog post title, author, date, main content, tags, and estimated reading time.',
    schema: JSON.stringify({
      type: 'object',
      properties: {
        title: { type: 'string' },
        author: { type: 'string' },
        date: { type: 'string' },
        content: { type: 'string' },
        tags: { type: 'array', items: { type: 'string' } },
        readingTimeMinutes: { type: 'number' },
        summary: { type: 'string' },
      },
      required: ['title', 'content'],
    }, null, 2),
  },
  {
    id: 'social-media',
    name: 'Social Media Post',
    description: 'Extract posts from social media pages (Twitter/X, LinkedIn, etc.)',
    prompt: 'Extract all social media posts/tweets visible on the page. For each post, get the author, content, timestamp, engagement metrics, and any media.',
    schema: JSON.stringify({
      type: 'object',
      properties: {
        posts: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              author: { type: 'string' },
              handle: { type: 'string' },
              content: { type: 'string' },
              timestamp: { type: 'string' },
              likes: { type: 'number' },
              reposts: { type: 'number' },
              replies: { type: 'number' },
              mediaUrls: { type: 'array', items: { type: 'string' } },
            },
          },
        },
      },
    }, null, 2),
  },
  {
    id: 'job-listing',
    name: 'Job Listing',
    description: 'Extract job posting details',
    prompt: 'Extract the job listing details including title, company, location, salary range, description, requirements, and benefits.',
    schema: JSON.stringify({
      type: 'object',
      properties: {
        title: { type: 'string' },
        company: { type: 'string' },
        location: { type: 'string' },
        remote: { type: 'boolean' },
        salaryMin: { type: 'number' },
        salaryMax: { type: 'number' },
        currency: { type: 'string' },
        description: { type: 'string' },
        requirements: { type: 'array', items: { type: 'string' } },
        benefits: { type: 'array', items: { type: 'string' } },
        employmentType: { type: 'string', enum: ['full_time', 'part_time', 'contract', 'internship'] },
        experienceLevel: { type: 'string' },
        postedDate: { type: 'string' },
      },
      required: ['title', 'company'],
    }, null, 2),
  },
  {
    id: 'restaurant',
    name: 'Restaurant / Business',
    description: 'Extract business details, hours, and contact info',
    prompt: 'Extract the business/restaurant information including name, address, phone, hours of operation, rating, and menu items if available.',
    schema: JSON.stringify({
      type: 'object',
      properties: {
        name: { type: 'string' },
        address: { type: 'string' },
        phone: { type: 'string' },
        website: { type: 'string' },
        rating: { type: 'number' },
        reviewCount: { type: 'number' },
        priceRange: { type: 'string' },
        cuisine: { type: 'string' },
        hours: { type: 'object', description: 'Day to hours mapping' },
        menuItems: { type: 'array', items: { type: 'object', properties: { name: { type: 'string' }, price: { type: 'number' } } } },
      },
      required: ['name'],
    }, null, 2),
  },
  {
    id: 'real-estate',
    name: 'Real Estate Listing',
    description: 'Extract property details from real estate listings',
    prompt: 'Extract property details including address, price, bedrooms, bathrooms, square footage, and listing description.',
    schema: JSON.stringify({
      type: 'object',
      properties: {
        address: { type: 'string' },
        price: { type: 'number' },
        currency: { type: 'string' },
        bedrooms: { type: 'number' },
        bathrooms: { type: 'number' },
        squareFeet: { type: 'number' },
        propertyType: { type: 'string', enum: ['house', 'apartment', 'condo', 'townhouse', 'land'] },
        description: { type: 'string' },
        images: { type: 'array', items: { type: 'string' } },
        yearBuilt: { type: 'number' },
        features: { type: 'array', items: { type: 'string' } },
      },
      required: ['address', 'price'],
    }, null, 2),
  },
  {
    id: 'event',
    name: 'Event',
    description: 'Extract event details (conferences, meetups, concerts)',
    prompt: 'Extract event information including title, date/time, venue, price, description, and organizer.',
    schema: JSON.stringify({
      type: 'object',
      properties: {
        title: { type: 'string' },
        date: { type: 'string' },
        time: { type: 'string' },
        venue: { type: 'string' },
        address: { type: 'string' },
        price: { type: 'string' },
        description: { type: 'string' },
        organizer: { type: 'string' },
        category: { type: 'string' },
        ticketUrl: { type: 'string' },
      },
      required: ['title', 'date'],
    }, null, 2),
  },
  {
    id: 'contact',
    name: 'Contact / People',
    description: 'Extract contact information and people details',
    prompt: 'Extract all contact information and people details from the page including names, titles, emails, phone numbers, and social links.',
    schema: JSON.stringify({
      type: 'object',
      properties: {
        people: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              name: { type: 'string' },
              title: { type: 'string' },
              email: { type: 'string' },
              phone: { type: 'string' },
              company: { type: 'string' },
              linkedin: { type: 'string' },
              twitter: { type: 'string' },
            },
          },
        },
      },
    }, null, 2),
  },
  {
    id: 'recipe',
    name: 'Recipe',
    description: 'Extract recipe details from cooking sites',
    prompt: 'Extract the recipe details including name, ingredients list, step-by-step instructions, prep time, cook time, and servings.',
    schema: JSON.stringify({
      type: 'object',
      properties: {
        name: { type: 'string' },
        description: { type: 'string' },
        ingredients: { type: 'array', items: { type: 'string' } },
        steps: { type: 'array', items: { type: 'string' } },
        prepTimeMinutes: { type: 'number' },
        cookTimeMinutes: { type: 'number' },
        servings: { type: 'number' },
        calories: { type: 'number' },
        cuisine: { type: 'string' },
        difficulty: { type: 'string', enum: ['easy', 'medium', 'hard'] },
      },
      required: ['name', 'ingredients', 'steps'],
    }, null, 2),
  },
];
